### ISSUE TITLE
ProductCategory should be it's own GraphQL type

### ISSUE THREAD

**Issue by jclangst** [silentshop/react#11]
proposed fields:
- id
- name
- descripton
- imageURL
- numberOfProducts
- products
- topProducts
- topSellers

Add to the top level query:
- categories: [ProductCategoryType]
- productsInCategory(categoryID) : [Product]

**Comment by jclangst** [comment]
@tylerthedeveloper This should be a priority because I need for the hierarchical category search which is basically the primary interface for shopping currently.

**Comment by tylerthedeveloper** [comment]
Updated to in progress

**Comment by jclangst** [comment]
It looks like Category does not have a resolver for its id. The id of any category is currently always null.

**Comment by tylerthedeveloper** [comment]
Added ID from firebase and manually returning the ID because null write results are just successes without data

**Comment by tylerthedeveloper** [comment]
closing this with local todos for:
topProducts
topSellers
