### ISSUE TITLE
Should have top level entry point for all sellers and sellers by category

### ISSUE THREAD

**Issue by jclangst** [silentshop/react#12]

**Comment by tylerthedeveloper** [comment]
/sellers is different from /users?

should we "tag" users once they list a product?

**Comment by jclangst** [comment]
What is your intent for ```/users```? I'm not sure if just seeing a list of everyone who signed up on the site will be useful for people looking to purchase products. Is there some sort of social networking functionality that you're planning on adding?

That said, we still need the graphql endpoint for ```user``` so that we can provide sellers the information of people who buy their products, but in the current site design that's the only use case (so the work you've done on this won't be wasted). The much more utilized endpoint set will be queries about "sellers" (a subset of the user table). Those endpoints are what I am asking for in this issue. 

As for the actual design of this, you won't tag users as sellers. Every product should have a field called ```sellerID```. You query the table of products and extract all ```sellerID```s. Then you link together the seller information for each ```sellerID``` from the ```user``` table (as well as any additional information about the products that sellers have available and maybe historical transaction data from a transaction and/or review table). "Tagging" users goes against data normalization principles and makes it easy to ruin your dataset by creating internal inconsistencies (i.e., someone marked as a seller because they once sold a product but they no longer have any products for sale) -- sidenote: this sort of "tagging" is a potential performance hack, but it would require much more testing and planning than we are currently investing in the infrastructure.

From a larger perspective, this highlights the primary weakness of nosql systems. As your data schema starts to grow into a big interrelational graph, just doing a simple (but critical from a UX perspective) operation like "get the top 10 rated sellers in the X product category" becomes 5+ separate (and relatively inefficient) queries on your database server. Every production-level nosql server has some ability to help developers optimize those sorts of demands, but there is a hard limit and to even reach that limit you have to have extensive knowledge about DBA. In the end, the schema that you are headed toward is much better for a relational system as the top layer with document-based sub layers for stuff like the transaction log. 

I don't know what your level of comfort with database administration is, but since we are using firebase, I assume low. As a result, I would just stick to the quick and dirty method of getting something that "works" no matter how inefficient it might be.... with the understanding that if you achieve any sort of significant scale, the entire backend data infrastructure will have to be redesigned (so don't spend a lot of time optimizing it). 

Does that make sense?

**Comment by JonAnderson5** [comment]
I agree, just a list of users will not be useful. The intent behind the users section originally was to provide a place for buyers to find reputable sellers and provide sellers with a digital "storefront".

Would it be better to get rid of the page displaying users/merchants altogether and have "seller rating/reputation" as a filter in each category page? If a buyer selects a product, the seller rating would be a selectable field that would provide brief but pertinent information on the seller's history? I assume buyers first look for a product then find a seller with a satisfactory rating and not the other way around, which makes me think the users page will not be visited often.

**Comment by tylerthedeveloper** [comment]
@jclangst  please see line 83 in the most recent commit
https://github.com/silentshop/react/commit/36df21df3c86789e09db5581e53e3a5739489599

**Comment by jclangst** [comment]
We can still have an entrypoint for the "sellers." I just wanted to narrow the scope from all "users." So now there is a top level tab just for sellers. I think that will be a convenient way to access seller "storefronts."

Within the product categories, it may be better to filter by product rating vs seller rating? This is what Amazon does. We could also provide both... just more work on the backend.

**Comment by tylerthedeveloper** [comment]
Added view via PSQL
