### ISSUE TITLE
Old Angular Site still doesn't work

### ISSUE THREAD

**Issue by jclangst** [silentshop/react#4]
"npm run start" doesn't work

**Comment by tylerthedeveloper** [comment]
**Old package scripts:**
ng serve = base run, no server (won't be able to access data)
**Updated client + server split:**
npm run proxy-serve (client using proxy for express)
node run server/lib/server.js

**Comment by jclangst** [comment]
I think the second command should just be 
```node server/lib/server.js```

**Comment by tylerthedeveloper** [comment]
Correct, apologies. It has been updated!

**Comment by tylerthedeveloper** [comment]
Can you verify it works now so we can close this one @jclangst

**Comment by jclangst** [comment]
It works.
