### ISSUE TITLE
Removal of Products Tab

### ISSUE THREAD

**Issue by jclangst** [silentshop/react#7]
Seems like the natural entry point would be to find a product in the following ways:

(1) Via popular (eventually user-tailored recommendation) products displayed on the home page
(2) Via a search interface on the home page
(3) Via hierarchical search by dissecting product categories

As a result, I don't think people will use a "products" tab that just has a massive index of all available products. As a result, we can save time by not developing that section.

**Comment by tylerthedeveloper** [comment]
I agree, good design choice.

This was solely serve in the initial wave of products before categorization makes sense.

We can leave it as a list for now with no special attention outside of a products query until we can sort out popular, home page, etc.
